### ISSUE TITLE
出现了异常信息，可能的原因为synccheeck的selector为4.

### ISSUE THREAD

**Issue by khao1110** [huoshan12345/WebQQWeChat#6]
[Action=同步检查, Result=错误, ErrorCode=ParameterError, ErrorMsg=Specified argument was out of the range of valid values.Parameter name: number[Specified argument was out of the range of valid values.
Parameter name: number], StackTrace=
   at FxUtility.Helpers.EnumHelper.ParseFromStrNum[T](String number)
   at WebWeChat.Im.Action.SyncCheckAction.HandleResponse(HttpResponseItem responseItem) in E:\cs\WebQQWeChat\src\WebWeChat\Im\Action\SyncCheckAction.cs:line 100
   at HttpAction.Action.AbstractHttpAction.<ExecuteAsync>d__26.MoveNext() in E:\cs\WebQQWeChat\src\HttpAction\Action\AbstractHttpAction.cs:line 86。

**Comment by huoshan12345** [comment]
已修
